name: CallBundleYML
run-name: CallBundleYML-PIPELINE
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: bla
        uses: QuiqueBarberan/bundlename@master
      - run: echo ${{ steps.xxxxx.outputs.BUNDLE }}
        shell: bash
