name: CallBundle
run-name: Show bundle variables
on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job1
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: QuiqueBarberan/bundlename@master
      - run: echo ${{ steps.foo.outputs.BUNDLE }}
        shell: bash
