name: CallBundleYML
run-name: CallBundleYML-PIPELINE
on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: pwd
      - id: stepbundle
        uses: QuiqueBarberan/bundlename@master
      - run: echo ${{ steps.bla.outputs.stepbundle }}
        shell: bash
